### ISSUE TITLE
Move read_mat_Witec() to **hySpc.read.Matlab**

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.mat#2]
... once that package exists.

**Comment by eoduniyi** [comment]
@GegznaV that was cool. There is so much to LEARN.

**Comment by bryanhanson** [comment]
Fixed via https://github.com/r-hyperspec/hySpc.read.mat/pull/4/commits/565c9e32ae74170a3619a114bc6ab84cd0e71320
